fix: resolve problem with Map type
fixing: Cannot find name 'Map'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.ts(2583)